---
abstract: "CPAN distribution implementing an XML grammar \nand a lightweight markup language for stories, novels and other fiction."
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Config: 0
  File::Find: 0
  File::Spec: 0
  Test::More: 0
  Test::XML: 0
  XML::LibXML: 0
  strict: 0
  warnings: 0
configure_requires:
  File::Spec: 0
  Module::Build: 0
  strict: 0
  warnings: 0
generated_by: 'Module::Build version 0.3607'
keywords:
  - authoring
  - cinema
  - 'creative writing'
  - films
  - grammar
  - movies
  - parsing
  - fiction
  - story
  - stories
  - noveilla
  - noveillas
  - novels
  - novel
  - writing
  - xml
  - xml-libxml
  - xslt
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Grammar-Fiction
provides:
  XML::Grammar::Fiction:
    file: lib/XML/Grammar/Fiction.pm
    version: v0.5.1
  XML::Grammar::Fiction::App::FromProto:
    file: lib/XML/Grammar/Fiction/App/FromProto.pm
    version: v0.5.1
  XML::Grammar::Fiction::App::ToDocBook:
    file: lib/XML/Grammar/Fiction/App/ToDocBook.pm
    version: v0.5.1
  XML::Grammar::Fiction::App::ToHTML:
    file: lib/XML/Grammar/Fiction/App/ToHTML.pm
    version: v0.5.1
  XML::Grammar::Fiction::Base:
    file: lib/XML/Grammar/Fiction/Base.pm
    version: v0.5.1
  XML::Grammar::Fiction::Err:
    file: lib/XML/Grammar/Fiction/Err.pm
    version: v0.5.1
  XML::Grammar::Fiction::Event:
    file: lib/XML/Grammar/Fiction/Event.pm
  XML::Grammar::Fiction::FromProto:
    file: lib/XML/Grammar/Fiction/FromProto.pm
    version: v0.5.1
  XML::Grammar::Fiction::FromProto::Node:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Comment:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Description:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Element:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::InnerDesc:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::List:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Paragraph:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Saying:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Text:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::WithContent:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Nodes:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
    version: v0.5.1
  XML::Grammar::Fiction::FromProto::Parser:
    file: lib/XML/Grammar/Fiction/FromProto/Parser.pm
    version: v0.5.1
  XML::Grammar::Fiction::FromProto::Parser::LineIterator:
    file: lib/XML/Grammar/Fiction/FromProto/Parser/LineIterator.pm
    version: v0.5.1
  XML::Grammar::Fiction::FromProto::Parser::QnD:
    file: lib/XML/Grammar/Fiction/FromProto/Parser/QnD.pm
    version: v0.5.1
  XML::Grammar::Fiction::FromProto::Parser::XmlIterator:
    file: lib/XML/Grammar/Fiction/FromProto/Parser/XmlIterator.pm
    version: v0.5.1
  XML::Grammar::Fiction::RNG_Renderer:
    file: lib/XML/Grammar/Fiction/RNG_Renderer.pm
  XML::Grammar::Fiction::Struct::Tag:
    file: lib/XML/Grammar/Fiction/Struct/Tag.pm
    version: v0.5.1
  XML::Grammar::Fiction::Struct::Tag::Para:
    file: lib/XML/Grammar/Fiction/Struct/Tag.pm
  XML::Grammar::Fiction::ToDocBook:
    file: lib/XML/Grammar/Fiction/ToDocBook.pm
    version: v0.5.1
  XML::Grammar::Fiction::ToHTML:
    file: lib/XML/Grammar/Fiction/ToHTML.pm
    version: v0.5.1
  XML::Grammar::FictionBase::TagsTree2XML:
    file: lib/XML/Grammar/FictionBase/TagsTree2XML.pm
  XML::Grammar::FictionBase::XSLT::Converter:
    file: lib/XML/Grammar/FictionBase/XSLT/Converter.pm
    version: v0.5.1
  XML::Grammar::Screenplay:
    file: lib/XML/Grammar/Screenplay.pm
    version: v0.5.1
  XML::Grammar::Screenplay::App::FromProto:
    file: lib/XML/Grammar/Screenplay/App/FromProto.pm
  XML::Grammar::Screenplay::App::ToDocBook:
    file: lib/XML/Grammar/Screenplay/App/ToDocBook.pm
  XML::Grammar::Screenplay::App::ToHTML:
    file: lib/XML/Grammar/Screenplay/App/ToHTML.pm
  XML::Grammar::Screenplay::Base:
    file: lib/XML/Grammar/Screenplay/Base.pm
  XML::Grammar::Screenplay::FromProto:
    file: lib/XML/Grammar/Screenplay/FromProto.pm
    version: v0.5.1
  XML::Grammar::Screenplay::FromProto::Parser:
    file: lib/XML/Grammar/Screenplay/FromProto/Parser.pm
  XML::Grammar::Screenplay::FromProto::Parser::QnD:
    file: lib/XML/Grammar/Screenplay/FromProto/Parser/QnD.pm
  XML::Grammar::Screenplay::ToDocBook:
    file: lib/XML/Grammar/Screenplay/ToDocBook.pm
    version: v0.5.1
  XML::Grammar::Screenplay::ToHTML:
    file: lib/XML/Grammar/Screenplay/ToHTML.pm
    version: v0.5.1
  XML::Grammar::Screenplay::ToTEI:
    file: lib/XML/Grammar/Screenplay/ToTEI.pm
    version: v0.5.1
  XML::Grammar::Screenplay::XSLT::Base:
    file: lib/XML/Grammar/Screenplay/XSLT/Base.pm
requires:
  Carp: 0
  Data::Dumper: 0
  Exception::Class: 0
  Exporter: 0
  File::ShareDir: 1.00
  Getopt::Long: 0
  HTML::Entities: 0
  List::Util: 0
  Moose: 0
  Parse::RecDescent: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
  XML::Writer: 0
  strict: 0
  warnings: 0
resources:
  homepage: http://www.shlomifish.org/open-source/projects/XML-Grammar/Fiction/
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://svn.berlios.de/svnroot/repos/web-cpan/XML-Grammar-Fiction/
version: v0.5.1
