---
abstract: "CPAN distribution implementing an XML grammar\nand a lightweight markup language for stories, novels and other fiction."
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Config: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::XML::Ordered: v0.0.5
  parent: 0
  utf8: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Grammar-Fiction
requires:
  Carp: 0
  Exception::Class: 0
  Exporter: 0
  File::ShareDir: 0
  File::Spec: 0
  Getopt::Long: 0
  HTML::Entities: 0
  List::MoreUtils: 0
  List::Util: 0
  MooX: 0
  MooX::late: 0.010
  XML::GrammarBase::Role::RelaxNG: 0
  XML::GrammarBase::Role::XSLT: v0.2.1
  XML::LibXML: 0
  XML::LibXSLT: 0
  XML::Writer: 0
  autodie: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=XML-Grammar-Fiction
  repository: ssh://hg@bitbucket.org/shlomif/perl-XML-Grammar-Fiction
version: 0.14.2
