---
abstract: "CPAN distribution implementing an XML grammar\nand a lightweight markup language for stories, novels and other fiction."
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::XML::Ordered: v0.0.5
  lib: 0
  parent: 0
  utf8: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.132830'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Grammar-Fiction
provides:
  XML::Grammar::Fiction:
    file: lib/XML/Grammar/Fiction.pm
    version: v0.14.8
  XML::Grammar::Fiction::App::FromProto:
    file: lib/XML/Grammar/Fiction/App/FromProto.pm
    version: v0.14.8
  XML::Grammar::Fiction::App::ToDocBook:
    file: lib/XML/Grammar/Fiction/App/ToDocBook.pm
    version: v0.14.8
  XML::Grammar::Fiction::App::ToHTML:
    file: lib/XML/Grammar/Fiction/App/ToHTML.pm
    version: v0.14.8
  XML::Grammar::Fiction::Err:
    file: lib/XML/Grammar/Fiction/Err.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto:
    file: lib/XML/Grammar/Fiction/FromProto.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node:
    file: lib/XML/Grammar/Fiction/FromProto/Node.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node::Comment:
    file: lib/XML/Grammar/Fiction/FromProto/Node/Comment.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node::Description:
    file: lib/XML/Grammar/Fiction/FromProto/Node/Description.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node::Element:
    file: lib/XML/Grammar/Fiction/FromProto/Node/Element.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node::InnerDesc:
    file: lib/XML/Grammar/Fiction/FromProto/Node/InnerDesc.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node::List:
    file: lib/XML/Grammar/Fiction/FromProto/Node/List.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node::Paragraph:
    file: lib/XML/Grammar/Fiction/FromProto/Node/Paragraph.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node::Saying:
    file: lib/XML/Grammar/Fiction/FromProto/Node/Saying.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node::Text:
    file: lib/XML/Grammar/Fiction/FromProto/Node/Text.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Node::WithContent:
    file: lib/XML/Grammar/Fiction/FromProto/Node/WithContent.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Parser:
    file: lib/XML/Grammar/Fiction/FromProto/Parser.pm
    version: v0.14.8
  XML::Grammar::Fiction::FromProto::Parser::QnD:
    file: lib/XML/Grammar/Fiction/FromProto/Parser/QnD.pm
    version: v0.14.8
  XML::Grammar::Fiction::Struct::Tag:
    file: lib/XML/Grammar/Fiction/Struct/Tag.pm
    version: v0.14.8
  XML::Grammar::Fiction::Struct::Tag::Para:
    file: lib/XML/Grammar/Fiction/Struct/Tag.pm
    version: v0.14.8
  XML::Grammar::Fiction::ToDocBook:
    file: lib/XML/Grammar/Fiction/ToDocBook.pm
    version: v0.14.8
  XML::Grammar::Fiction::ToHTML:
    file: lib/XML/Grammar/Fiction/ToHTML.pm
    version: v0.14.8
  XML::Grammar::FictionBase::Event:
    file: lib/XML/Grammar/FictionBase/Event.pm
    version: v0.14.8
  XML::Grammar::FictionBase::FromProto::Parser::LineIterator:
    file: lib/XML/Grammar/FictionBase/FromProto/Parser/LineIterator.pm
    version: v0.14.8
  XML::Grammar::FictionBase::FromProto::Parser::XmlIterator:
    file: lib/XML/Grammar/FictionBase/FromProto/Parser/XmlIterator.pm
    version: v0.14.8
  XML::Grammar::FictionBase::TagsTree2XML:
    file: lib/XML/Grammar/FictionBase/TagsTree2XML.pm
    version: v0.14.8
  XML::Grammar::FictionBase::XSLT::Converter:
    file: lib/XML/Grammar/FictionBase/XSLT/Converter.pm
    version: v0.14.8
  XML::Grammar::Screenplay:
    file: lib/XML/Grammar/Screenplay.pm
    version: v0.14.8
  XML::Grammar::Screenplay::App::FromProto:
    file: lib/XML/Grammar/Screenplay/App/FromProto.pm
    version: v0.14.8
  XML::Grammar::Screenplay::App::ToDocBook:
    file: lib/XML/Grammar/Screenplay/App/ToDocBook.pm
    version: v0.14.8
  XML::Grammar::Screenplay::App::ToHTML:
    file: lib/XML/Grammar/Screenplay/App/ToHTML.pm
    version: v0.14.8
  XML::Grammar::Screenplay::Base:
    file: lib/XML/Grammar/Screenplay/Base.pm
    version: v0.14.8
  XML::Grammar::Screenplay::FromProto:
    file: lib/XML/Grammar/Screenplay/FromProto.pm
    version: v0.14.8
  XML::Grammar::Screenplay::FromProto::Parser:
    file: lib/XML/Grammar/Screenplay/FromProto/Parser.pm
    version: v0.14.8
  XML::Grammar::Screenplay::FromProto::Parser::QnD:
    file: lib/XML/Grammar/Screenplay/FromProto/Parser/QnD.pm
    version: v0.14.8
  XML::Grammar::Screenplay::ToDocBook:
    file: lib/XML/Grammar/Screenplay/ToDocBook.pm
    version: v0.14.8
  XML::Grammar::Screenplay::ToHTML:
    file: lib/XML/Grammar/Screenplay/ToHTML.pm
    version: v0.14.8
  XML::Grammar::Screenplay::ToTEI:
    file: lib/XML/Grammar/Screenplay/ToTEI.pm
    version: v0.14.8
requires:
  Carp: 0
  Exception::Class: 0
  Exporter: 0
  File::ShareDir: 0
  File::Spec: 0
  Getopt::Long: 0
  HTML::Entities: 0
  List::MoreUtils: 0
  List::Util: 0
  MooX: 0
  MooX::late: 0.010
  XML::GrammarBase::Role::RelaxNG: v0.2.2
  XML::GrammarBase::Role::XSLT: v0.2.2
  XML::LibXML: 0
  XML::LibXSLT: 0
  XML::Writer: 0
  autodie: 0
  base: 0
  perl: 5.014
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=XML-Grammar-Fiction
  repository: ssh://hg@bitbucket.org/shlomif/perl-XML-Grammar-Fiction
version: 0.14.8
