---
name: XML-Grammar-Fiction
version: v0.0.1
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: |-
  CPAN distribution implementing an XML grammar 
  and a lightweight markup language for stories, novels and other fiction.
license: mit
resources:
  homepage: http://web-cpan.berlios.de/modules/XML-Grammar-Fiction/
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://svn.berlios.de/svnroot/repos/web-cpan/XML-Grammar-Fiction/
build_requires:
  Config: 0
  File::Find: 0
  File::Spec: 0
  Test::More: 0
  Test::XML: 0
  XML::LibXML: 0
  strict: 0
  warnings: 0
requires:
  Carp: 0
  Data::Dumper: 0
  Getopt::Long: 0
  HTML::Entities: 0
  List::Util: 0
  Moose: 0
  Parse::RecDescent: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
  XML::Writer: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.35
provides:
  XML::Grammar::Fiction:
    file: lib/XML/Grammar/Fiction.pm
    version: v0.0.1
  XML::Grammar::Fiction::App::FromProto:
    file: lib/XML/Grammar/Fiction/App/FromProto.pm
    version: v0.0.1
  XML::Grammar::Fiction::App::ToDocBook:
    file: lib/XML/Grammar/Fiction/App/ToDocBook.pm
    version: v0.0.1
  XML::Grammar::Fiction::App::ToHTML:
    file: lib/XML/Grammar/Fiction/App/ToHTML.pm
    version: v0.0.1
  XML::Grammar::Fiction::Base:
    file: lib/XML/Grammar/Fiction/Base.pm
    version: v0.0.1
  XML::Grammar::Fiction::FromProto:
    file: lib/XML/Grammar/Fiction/FromProto.pm
    version: v0.0.1
  XML::Grammar::Fiction::FromProto::Node:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Comment:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Description:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Element:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::InnerDesc:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::List:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Paragraph:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Saying:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::Text:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Node::WithContent:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
  XML::Grammar::Fiction::FromProto::Nodes:
    file: lib/XML/Grammar/Fiction/FromProto/Nodes.pm
    version: v0.0.1
  XML::Grammar::Fiction::FromProto::Parser:
    file: lib/XML/Grammar/Fiction/FromProto/Parser.pm
    version: v0.0.1
  XML::Grammar::Fiction::FromProto::Parser::QnD:
    file: lib/XML/Grammar/Fiction/FromProto/Parser/QnD.pm
    version: v0.0.1
  XML::Grammar::Fiction::ToDocBook:
    file: lib/XML/Grammar/Fiction/ToDocBook.pm
    version: v0.0.1
  XML::Grammar::Fiction::ToHTML:
    file: lib/XML/Grammar/Fiction/ToHTML.pm
    version: v0.0.1
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - authoring
  - cinema
  - creative writing
  - films
  - grammar
  - movies
  - parsing
  - fiction
  - story
  - stories
  - noveilla
  - noveillas
  - novels
  - novel
  - writing
  - xml
  - xml-libxml
  - xslt
